[build-system]
requires = ["scikit-build-core", "nanobind", "numpy"]
build-backend = "scikit_build_core.build"


[project]
name = "pymfem"
version = "0.0.1"
dependencies = [
    "numpy>=1.20.0",
    "numba",
    "numba-scipy",
    "scipy"
]